### ISSUE TITLE
[BUG] Not sure if I'm missing something

### ISSUE THREAD

**Issue by the-bort-the** [tobychui/zoraxy#1]
**Describe the bug**
After cloning, I'm not seeing how I'd run `sudo ./zoraxy -port=:8000` - is this file somewhere else?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser (if it is a bug appears on the UI section of the system):**
 - OS: Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
 - Version: latest

**Host Environment (please complete the following information):**
-  Arch: [e.g. arm64]
 - Device: [e.g. Bananapi R2 PRO]
 - OS: [e.g. Armbian]
 - Version [e.g.  23.02 Bullseye ]

**Additional context**

**Comment by tobychui** [comment]
Hi @the-bort-the,

Currently the project is still in development. If you want to try it out, you can use the release binary at https://github.com/tobychui/zoraxy/releases/tag/2.5

Otherwise, you will need a Go compiler to build the executable. You can do the following if you want to build from source.
```
git clone https://github.com/tobychui/zoraxy
cd zoraxy/src/
go build
sudo ./zoraxy -port=:8000
``

These will be on the website after I have finished the web design (hopefully within 2 -  3 days). In the mean-time, I would recommend you to try out the system using binary executable.
