### ISSUE TITLE
[BUG] Uptime not accurate

### ISSUE THREAD

**Issue by RickoT** [tobychui/zoraxy#121]
**Describe the bug**
The uptime indicator is inaccurate if there is a redirect to a namespace (for example airsonic server shows "Target online but not accessible" because it returns a 403 before it redirects to the login screen)

**To Reproduce**
1. Create an airsonic docker container
2. configure for reverse proxy
3. Create a reverse proxy to the docker container
4. Watch monitor

**Expected behavior**
Check should follow redirects to make sure the site is up before indicating it is down

**Host Environment (please complete the following information):**
-  Arch: AMD64
 - Device: Docker
 - OS: Debian 12.5

**Additional context**
It would be nice to be able to adjust the health check to a specific URL if necessary

**Comment by tobychui** [comment]
403 Forbidden means not accessible, and if a redirect is needed, the back end should response with 3xx. If there is a redirection done with 403, it means it is done using HTML tags or JavaScript located in the body section of the requested page.

Zoraxy only request for header in uptime to reduce resources usage, so the uptime said "Target online but not accessible" is a very accurate description. The issue here is the back end server where you are reverse proxying (airsonic server I guess?) do not follow standards HTTP guideline on how to correctly handle redirects. 

There is nothing I can do except telling you that these error message and color blocks were from this html file. If you don't like seeing orange blocks, you can change them to other colors. 

https://github.com/tobychui/zoraxy/blob/2cdd5654ed898651482883ed08d9d9b79da095ef/src/web/components/uptime.html#L166
