### ISSUE TITLE
[BUG] High cpu usage on big file download

### ISSUE THREAD

**Issue by openaspace** [tobychui/zoraxy#142]
Hello, your system is wonderful... but i tried to use in front of my webdav file transfer system and when an user download a big file like a simple 3gb over tcp, the cpu usage reach 50% .. is really really high!!!

My nginx proxy remain around 5% for the same transfer.
Also, using cloudflare dns with cloudflare record A proxy disabled and forward real ip enabled in the proxy, if geoip is set with different US allowed country , connections are denied. 

Please verify .. for now i will place it in standbye.

**Comment by tobychui** [comment]
@openaspace The bug template is here for a reason. With the information you given, I can think of a lot of reasons which includes your CPU is too weak or you have a wrong settings somewhere. Here is the template if you can't find it.

-------

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Browser (if it is a bug appears on the UI section of the system):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Host Environment (please complete the following information):**
-  Arch: [e.g. arm64]
 - Device: [e.g. Bananapi R2 PRO]
 - OS: [e.g. Armbian]
 - Version [e.g.  23.02 Bullseye ]

**Additional context**
Add any other context about the problem here.

**Comment by tobychui** [comment]
@openaspace Please fill in the template with the information about what webdav server you are using, what OS you are using and so on, otherwise I cannot help you on debugging the situation.

**Comment by tobychui** [comment]
> the cpu usage reach 50%

I just uploaded a 600MB and 1.07GB file to ArozOS WebDAV via Zoraxy v3.0.3, and my server's CPU is 10 years dual core G3258, didn't see any issues related to high CPU usage. 

>  if geoip is set with different US allowed country , connections are denied.

Not sure what you mean, are you using the correct access filter that you have set black/whitelist on?

**Comment by tobychui** [comment]
Closing due to inactive and unable to reproduce issues.
