### ISSUE TITLE
[ENHANCEMENTS] Configure reverse proxy using docker labels

### ISSUE THREAD

**Issue by kinchahoy** [tobychui/zoraxy#156]
**Is your feature request related to a problem? Please describe.**
I switched between a few reverse proxy systems until I figured out that I could use https://github.com/lucaslorentz/caddy-docker-proxy to auto configure my reverse proxy via docker labels. While Caddyfiles are wierdly complicated, it would be amazing if you could autogenerate reverse proxy settings from docker labels (essentially just subdomain.domain.duckdns.org + port)

**Comment by tobychui** [comment]
Hi @kinchahoy , 

I don't personally use docker for my setup so I have no idea how this can be done. But I guess @PassiveLemon should have some clues on how this can be achieved.

**Comment by PassiveLemon** [comment]
Personally, I think this is fairly out of scope. While it would be a neat idea, I feel its a bit of a complicated setup for something that is intended to be configured through a GUI.

**Comment by tobychui** [comment]
This give me a feeling that this is a typical X-Y problem kind of feature request. So in summary, you want a service discovery tool for listing all the existing service by port scanning? 

Also one thing worth mentioning is that Zoraxy is not designed for running inside docker. Many features like mDNS discovery, IP scanning and WoL don't work in docker, so optimizing docker user experience will not be inside my to-do list any time soon.

**Comment by tobychui** [comment]
@kinchahoy Hmmm I guess you misunderstood something. 

Zoraxy is not a startup company nor a commercial project. There are no "target market", I contribute the code myself for my homelab which runs on a distributed NUCs and Raspberry Pis cluster (and didn't use docker). All features you saw in README exists because someone needs it and contributed it into the code base. I do help a bit in tidying them up or fixing minor bugs, but that is what I would do for a feature I don't personally needs. 

If you really want this feature, my suggestion will be creating a pull request to this project that add such feature or wait for someone else who also need it and pick up this feature request.

**Comment by Morethanevil** [comment]
> The point is that if you are standing up a service behind a reverse proxy, you want to stand it up with the reverse proxy, not stand it up, then go setup the reverse proxy as an unncessary next step.
> 
> Now, of course, if you are not designing for docker, or to front-end services running on docker, then it doesn't make sense.
> 
> Can I ask though ... who's the target market for Zoraxy? Who's running a homelab but not running services in containers in 2024? How are they running them? VMs?

I use Zoraxy on my hostsystem without docker. Why? Because it can then reach all my services, within a VM, LXC, docker or the host itself. If it would only run in docker, I could not reach services within LXC and vice versa. For example Nextcloud is running on the host for performance reasons, Vaultwarden within docker for an isolated environment. Searx-NG the same. WordPress is running on the host, same as Nextcloud for performance reasons and a second testing installation is running in LXC, so it does not cause problems with the main page.


Almost every service you use in a container has an installguide and there is always a port to use mentioned in it. If you don't know which port your app is listening in docker, you can take a look in Portainer. I have [written a guide](https://github.com/tobychui/zoraxy/wiki/Zoraxy-in-Docker-with-Portainer-and-Nginx-as-examples) to setup Zoraxy in docker and connect it Portainer. I think this will be enough for most users. Mostly the users switch from Nginx proxy manager and it has no docker labels support too.

Docker is a great thing for running services easily and sure has its beneftis, but I don't need every service within a container. MinIO for example is just a single binary, like Adguard, so I can run them directly with just a single command.

**Comment by tobychui** [comment]
Closing this as this as this enhancement request does not align with Zoraxy design goal. 
As always, PRs are welcomed 👍🏻
