### ISSUE TITLE
[ENHANCEMENTS] Redirects

### ISSUE THREAD

**Issue by boehamian** [tobychui/zoraxy#173]
**Is your feature request related to a problem? Please describe.**
No 
**Describe the solution you'd like**
Got to do redirects for CardDAV and calDAV for nextcloud server. No sure if this has been implemented or where to put. 

**Describe alternatives you've considered**
Have considered moving to Nginx proxy manager but given the issues with it at the moment I am reluctant.

**Additional context**
This is the settings I need to put forward for nextcloud https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html

**Comment by tobychui** [comment]
There is an item named "Redirection" in the side menu.
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/57efff48-4c38-4ec8-9d23-37fb035f5fe9)

The redirect rules is applied globally instead of per HTTP proxy rule. Use your full domain in the matching rule (e.g. nextcloud.yourdomain.com/.well-known/carddav) and point it to your NextCloud server (e.g. your_nextcloud_instance_ip_addr:port/remote.php/dav/). You can also enable regex but that tends to slow down the whole proxy server.
