### ISSUE TITLE
Option to Choose Custom Certificate Selection for HTTP Proxy Hosts [ENHANCEMENTS]

### ISSUE THREAD

**Issue by vineethmn** [tobychui/zoraxy#177]
Description:

It would be highly beneficial to add the ability to select or change the SSL certificate for an existing HTTP Proxy host, similar to the functionality provided by Nginx Proxy Manager (NPM). Currently, it seems that we can only use the certificate generated when initially adding the HTTP Proxy host.

Current Issue:

I attempted to upload a custom wildcard certificate, but there is no option to use it. The existing dedicated certificate, which was generated during the initial setup of the proxy host, is the only available choice.

Proposed Solution:

Implement a feature that allows users to select from existing certificates or upload new ones when configuring or updating an HTTP Proxy host.

**Comment by tobychui** [comment]
No. In Zoraxy, we try to make things automatic. 

The certificate is chosen automatically by Zoraxy. Make sure your wildcard cert hostname is set correctly (e.g. `*.example.com` then you can name it as `example.com`) and Zoraxy should pick the correct one for you. 

If you are using it as the default certificate for all your HTTP proxy hosts (i.e. all your domains and sub-domains are covered in one wildcard cert), upload it to the "Fallback Certificate" section. 

Otherwise, it might be an issue of the automatic cert selection logic and you might need open a bug report to provide more information for debugging.

**Comment by tobychui** [comment]
I am not sure I understand you correctly, but you can upload your custom SSL certificates into Zoraxy and lets zoraxy SNI do the job. SNI works with both automatic generated certificates via ACME and user uploaded one. Unless your use case is so complex and entered into the custom CA kind of things (mostly for enterprise uses) , then I would suggest you to go with [Caddy](https://caddyserver.com/). 

Adding manual options in Zoraxy is like adding manual transmission into an electric car. If a you picks an electric car, you should not expected the car to have a gear stick. Or maybe you can describe your use cases in great details to see if it is actually meaningful to implement such feature in Zoraxy?
