### ISSUE TITLE
Failed to verify Certificate when not using localhost as proxy destination

### ISSUE THREAD

**Issue by PMFRTT** [tobychui/zoraxy#2]
When running in docker, the proxy destination will never be localhost. but rather a destination inside the local network.
When adding a destination, where the proxy address has self-signed SSL enabled, like so:
![image](https://github.com/tobychui/zoraxy/assets/37709302/5d209328-fd6e-42aa-b751-d87018103ed7)
and the certificate is only valid for localhost:
![image](https://github.com/tobychui/zoraxy/assets/37709302/0238ed70-469f-4111-befe-c523160229c4)
is there any way to skip the validation of the local certificate in Zoraxy?

Whenever i try to configure a proxy host this way, i get the following error in my Browser:
![image](https://github.com/tobychui/zoraxy/assets/37709302/ca7713e8-8812-4c96-9898-2268de46ee7a)

The log of Zoraxy gives me the following error:
![image](https://github.com/tobychui/zoraxy/assets/37709302/da91baba-478c-4c13-a7b8-76cd483e99f3)

Any help with this issue would be greatly appreciated!

**Comment by tobychui** [comment]
I think this would be a complicated issue to solve. I see there are similar issues with apache proxy_http module as well (with docker environment, mostly). 

The easiest way to solve this issue is adding a CA to your environment manually. This will trick the system to think that your cert is valid and Zoraxy will continue processing the proxy request.

The current way Zoraxy proxy https is using the http.Hijacker method in http.Server package. If a validation bypass is needed, I guess I might need to rewrite the whole HTTPS proxy logic to [allow transporter to skip TLS verification](https://stackoverflow.com/questions/12122159/how-to-do-a-https-request-with-bad-certificate). I will see how could I deal with this after the major functions are completed.

**Comment by tobychui** [comment]
Issue fixed in v2.6.1. You can find the option under "Create Proxy Rules" > Advance Settings > Ignore TLS/SSL Verification Error
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/f1a6d14b-320e-4228-b0db-15a8ec5e85a2)

Though, I do not recommend this for the following reasons.
1. If you are setting up your servers in a trusted network (e.g. home network), you don't need https
2. If you are setting up your proxy to point to a remote address, a valid certificate is always recommended for security reasons
3. If you want to self-sign a cert for your domain, you should setup a custom CA that verify your certificate on your reverse proxy host environment instead of bypassing the error

But still, the options are here so if you need it for testing anything, you can feel free to use it with your own risk.
