### ISSUE TITLE
[ENHANCEMENTS] Listen on other ports

### ISSUE THREAD

**Issue by thytetgc** [tobychui/zoraxy#244]
In my current NPM, I can listen on any port and send it to another destination port, using the parameter [listen PORT_XX ssl;]

In Zoraxy, even creating a proxy rule using the format [sub.domain.com:PORT_XX] it does not create a listener for that port.

It would be very important to have this functionality.

I'm using version 3.0.8

**Comment by tobychui** [comment]
Zoraxy only listen to a single inbound port which is 443 (and if you includes the port 80 then 2 ports). 

This is by design and if you want to listen to multiple ports, you can use multiple instance of zoraxy or using stream proxy (TCP mode) to forward your alternative port(e.g. 8443) to primary port (e.g. 443). Listening to mult-inbound port with different hostname is out of the scope of homelab self-hosting, I do considering of a commercial version that support this but for now, we have no plans in adding support for multi-inbound ports with user define hostname groups.

Thanks for asking :)

**Comment by thytetgc** [comment]
Still no news about this feature? Many people haven't migrated from NPM just because this option is missing!
