### ISSUE TITLE
[BUG] Websocket not working with Audiobookshelf

### ISSUE THREAD

**Issue by ExXxtr3me** [tobychui/zoraxy#282]
**Describe the bug**
I'm using Audiobookshelf as docker on my unraid server, the android app on my phone is telling me that the websocket connection can't be established. I'm pretty sure it was working until version 3.07. I also tested it with Nginx Proxy Manager, websocket is working there. 

**To Reproduce**
1. Connect the Android app to the existing audiobookshelf server
2. Log in is working, but websocket is not.

**Screenshots**
![Screenshot_20240815-085050](https://github.com/user-attachments/assets/9e1cdc5f-0a1b-4af0-9e21-323116a81512)

**Browser (if it is a bug appears on the UI section of the system):**
 - OS: Android
 - Version 3.10

**Host Environment (please complete the following information):**
-  Arch: Docker
 - OS: unraid
 - Docker Version 3.10

**Comment by tobychui** [comment]
Hi @ExXxtr3me 

The only things changed regarding dynamic proxy module since v3.0.7 are the followings
- Added support for Proxmox (this won't trigger unless you have PVE related cookies)
- Added bypass option for hop-by-hop headers and force host header rewrite (also will not trigger if websocket upgrade header is detected)

I have just checked websocket and it is working normally on other open source projects that uses this protocol. As "websocket is not working on my app" is not informative in anyway to help debug this issue, maybe you can try deleting the related proxy rule and add it again? Or sometime it might be issues related to cookie / cache that you might need to clear the app data. If you can provide more debug information, maybe I can figure out something for you.

**Comment by ExXxtr3me** [comment]
Thanks for your help, deleting the rule and recreating it fixed the problem. 👍👍👍
