### ISSUE TITLE
[ENHANCEMENTS]

### ISSUE THREAD

**Issue by Nasa1423** [tobychui/zoraxy#283]
**Is your feature request related to a problem? Please describe.**
When Zoraxy is deployed on server, it is vulnerable to the MITM. When trying to point http proxy on Zoraxy itself it is showing loopback warning.

**Describe the solution you'd like**
Generating SSL cert for domain pointed on the server and using this domain for accessing panel.

**Describe alternatives you've considered**
Allowing to loopback single domain to the admin panel

**Additional context**
Nothing here.

**Comment by tobychui** [comment]
Hi @Nasa1423 

Ok, here are two problem you raised here. Let me explain it in details.
1. You **should not expose Zoraxy management interface to the public internet**. If you want to access your management interface, the correct & secure way to do so is only allow access in local area network / trusted network. However, I understand that some people just don't care about security and want to have a quick UI for tinkering, so I also allowed users to setup HTTP proxy rule that point back to the management interface, which causes the "loopback warning" in (2)
2. **The loopback warning disabled some settings which if changed, will effect / take down the management interface HTTPS reverse proxy.** (i.e. if you changed the disabled settings, you will not be able to know if the change is done successfully as the connection to backend is closed). That is why it is disabled and warn you that you should not touch these settings even if you decided to expose the interface to the public internet. In fact, you can still change other settings via HTTPS and your way to do it (and seeing the loopback warning) is perfectly normal.

I will label this as won't fix now as it is the intended design for loopback mode. If you have further questions, feel free to comment below even if the issue is closed.
