### ISSUE TITLE
[HELP] How to use private IP range in access rule?

### ISSUE THREAD

**Issue by Lexxior** [tobychui/zoraxy#334]
**What happened?**
I can't access my domains from my LAN when adding my subnet (192.168.1.0/24) to the access rule, it works only with my public IP, which is dynamic and changes regularly.

**Describe what have you tried**
Changing the config according to tips from existing issues

**Describe the networking setup you are using**
docker, latest version

I need help to configure my network so I can access the domains from within my LAN

**Comment by tobychui** [comment]
@Lexxior This happens because your domain is resolved to your public IP address and when you are connect to it (via your web browser, for example), your computer is actually requesting your public IP address. From Zoraxy perspective, you are accessing from WAN using your own public IP address of your router (if you are hosting your setup at home).

The proper fix is following @Orko79  recommendation and setup your DNS service correctly or just whitelist your own public IP address in the access rule.

**Comment by Lexxior** [comment]
Thanks, I had to add each subdomain in pihole /etc/pihole/custom.list individually, now it works
like this:

```
192.168.1.111 web.mydomain.com
192.168.1.111 dav.mydomain.com
```
