### ISSUE TITLE
[ENHANCEMENTS] Allow for custom Whitelist/Blacklist result

### ISSUE THREAD

**Issue by fyr77** [tobychui/zoraxy#38]
**Is your feature request related to a problem? Please describe.**
Currently, when using the whitelist or blacklist, HTTP status 403 is returned to anyone blocked. 

**Describe the solution you'd like**
It would be nice to be able to return something different (such as a "sorry not available in your country") or redirect to another page or even a custom html page.

**Describe alternatives you've considered**
- Not use the blocklist: not an option for my use case
- Use another software such as caddy, which has this feature but no nice GUI like zoraxy.

**Comment by tobychui** [comment]
@fyr77 Actually I do have a template for the black / white list 403 respond body, which looks like this.
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/de239509-3520-409d-a4d4-fe0618ed242a)

But I forgotten to include it into the go:embed. So that is why it falls back to a blank page with 403 HTTP Error.
I am working on it with the static web server function for customizable, I guess it will still take me a month or more to make it working (as I only work on this project in my free time).

In the mean time, you can modify this line in main.go and set this to true
```
development = false //Set this to false to use embedded web fs
```
and then modify the template (/web/forbidden.html) in the web folder for a temporary solution.
