### ISSUE TITLE
[BUG] ZeroTier not fully disabled

### ISSUE THREAD

**Issue by LeonardoIz** [tobychui/zoraxy#388]
**Describe the bug**
Even if zerotier is disabled, it is reported as Link Error, and it also automatically creates a volume in the container

**To Reproduce**
Create a container with the latest version and manually disable ZeroTier in the environment variables

**Expected behavior**
Appear as disabled, and do not create the volume automatically

**Screenshots**
![image](https://github.com/user-attachments/assets/7fe07dc5-a86d-4d5d-a6cd-e17ee8f4049a)
![image](https://github.com/user-attachments/assets/6c7ae9c3-5ed4-4da1-a712-ae79576d6730)
![image](https://github.com/user-attachments/assets/6b568c51-6999-4647-b005-3c4a9a6579fb)

**Host Environment (please complete the following information):**
 -  Arch: amd64
 - OS: Ubuntu Server
 - Version 22.04
 - Docker Version: 3.1.2

**Comment by PassiveLemon** [comment]
Could you report what is in the volume, if anything at all?

**Comment by LeonardoIz** [comment]
It is empty 
![image](https://github.com/user-attachments/assets/7dc6b887-fc7a-41c5-b3be-5015be1ece97)

**Comment by PassiveLemon** [comment]
The volume is created from the VOLUME instruction in the Dockerfile. If a host mount is not supplied at the same location as the volume, then Docker will create the volume. Unfortunately, we can't create a volume at runtime.

I think I could set up a symlink so that when ZeroTier is used, the data is stored in the Zoraxy volume. I'll look into it
