### ISSUE TITLE
[ENHANCEMENTS] Dark Mode PLEASE

### ISSUE THREAD

**Issue by NightHawkATL** [tobychui/zoraxy#390]
**Is your feature request related to a problem? Please describe.**
The site is too bright

**Describe the solution you'd like**
Add an option to change between dark mode and super bright mode.

**Describe alternatives you've considered**
Dark Reader is the only option but I don't like having it enabled all the time.

**Additional context**
A lot of devs will thank you!

**Comment by tobychui** [comment]
It is already work in progress. Here is a quick preview for you.

![圖片](https://github.com/user-attachments/assets/9fa540a8-a7e2-4e87-9489-9dd6e5a28f28)

As Semantic UI do not support dark theme, I am writing the css override manually and it will take tons of time. So you can expect the progress to be slow. 

![圖片](https://github.com/user-attachments/assets/82a87c76-259d-4ba7-b2e9-c5fa31f6bd0d)

**Comment by tobychui** [comment]
Might take another week to wrap things up. But it now looks even better with new color scheme! 

![圖片](https://github.com/user-attachments/assets/3593cafb-8638-4a77-ba81-02c78c50f58c)

![圖片](https://github.com/user-attachments/assets/49b847c0-74cb-46e6-8724-7d7f75e0fdd0)

![圖片](https://github.com/user-attachments/assets/0a0df34d-a202-4af2-9223-d5d05c6c3207)

For the record, this is done using all css class based switching. So switching speed is super fast. 

https://github.com/user-attachments/assets/7a2cf96d-a389-460d-a385-4d03054ca0d1

**Comment by tobychui** [comment]
@NightHawkATL Seems your homelab has some serious things running inside. 

Yes, Zoraxy is tends to be slower when compared to Nginx or Caddy due to many of the automation in the request handling logic. A system with complex manual configuration is much more optimized for tons of smaller packets transfer (compared to Zoraxy which mainly design to serve webpages) as request overhead is an issue in Zoraxy that need to be optimized later.

Feel free to check back later after you have tired of NPM again and want a switch :)

**Comment by tobychui** [comment]
Dark theme mode (Experimental) added in v3.1.4.
