### ISSUE TITLE
[HELP] Increasing of the Upload Limit

### ISSUE THREAD

**Issue by qMalte** [tobychui/zoraxy#413]
Where can I increase the upload limit or the maximum size of a request? Currently, file uploads via the proxy return a timeout (HttpStatus: 408) after a while.

Does Zoraxy offer a possibility there?

**Comment by tobychui** [comment]
Hi @qMalte 

Zoraxy use steam bases copy for proxying the request and do not have a upper limit on payload size. However the transport layer do impose a time out value but that should rarely be reached unless your network is really slow (or you are sending something so larger that usually should be sent via other methods like FTP, multipart form data or Websocket)

Can you check how long that time out error shows up after you started the upload? If it is under 5 minutes it should be caused by  issues other than upload size or timeout.

**Comment by qMalte** [comment]
Hi @tobychui 

Thank you for the information.

In my case it is about multipart POST requests that time out after a while.

Is there a way to increase the 5 minutes you mentioned (default value) or is this not advisable and I should transfer larger files from client to server using a different method?

**Comment by tobychui** [comment]
@qMalte The proper way to upload large file is split it into smaller chunks in front-end and upload it to different server on the backend or at least, send chunk by chunk so you can also support some modern features like pause / resume uploads for large files. 

I plans to add a customizable timeout value for the dpcore as stated in #387, but it is quite a large change and you might need to wait for a bit before it is available in Zoraxy. That being said, Zoraxy is design to automate tons of things to fit 90% of the use cases, and uploading a large file with a single form post and slow internet is not one of them (at least for now) 😆

**Comment by qMalte** [comment]
@tobychui 

All right, thanks for the information and the tips on what best practice could look like.

P.S. Zoraxy is a really nice product :)
