### ISSUE TITLE
[BUG] Missing Headers 

### ISSUE THREAD

**Issue by lastsamurai26** [tobychui/zoraxy#420]
i checked my Headers via securityheaders.com 

Zoraxy
![image](https://github.com/user-attachments/assets/7e9891d2-e2c9-4954-ab9b-15d0b537e339)

Nginx Proxy Manager standard 
![image](https://github.com/user-attachments/assets/17cd39d0-9d00-460a-ac99-0a94ba838827)

I found out that i can activated only HSTS and Permission policy as a silder
I moved over back to NPM but I actually switched to Zoraxy because npm does not have working access lists  :-(

**Comment by tobychui** [comment]
@lastsamurai26 That is actually a good question to ask and no, it is not a bug. 

Do you know why only HSTS and Permission policy got a slider but not the others? That is because you need to manually set them according to your use cases to not screw up things in your upstream.  If you are too busy to do so, you can just copy the settings I am using on my homelab and paste them into your routing rules as custom headers for appending in responses (Zoraxy to downstream / client devices).

```
content-security-policy: default-src * 'unsafe-inline' 'unsafe-eval'; script-src * 'unsafe-inline' 'unsafe-eval'; connect-src * 'unsafe-inline'; img-src * data: blob: 'unsafe-inline'; font-src 'self' * data:; frame-src *; style-src * 'unsafe-inline';
x-frame-options: ALLOW-FROM *
referrer-policy: strict-origin-when-cross-origin
x-content-type-options: nosniff
```

Use with your own risk 👍🏻
