### ISSUE TITLE
[ENHANCEMENTS] Add toggle in Set Proxy Root to redirect not found subdomain to root domain with ssl

### ISSUE THREAD

**Issue by stevewas** [tobychui/zoraxy#46]
**Is your feature request related to a problem? Please describe.**
When trying to visit a non-valid subdomain route, it currently keeps the URL and responds with a self-signed Zoraxy cert, I would like the ability to redirect back to the root domain and have it use one of the ACME certs i generated.

eg
nonexisting.abc.xyz keeps the name and replies with a self-signed cert
<img width="564" alt="Screen Shot 2023-08-19 at 2 25 06 PM" src="https://github.com/tobychui/zoraxy/assets/82685579/0c3a7a84-7455-4a35-9774-db93cd71d3b3">

**Describe the solution you'd like**
option 1.
In the Set Proxy Root page, I would like a toggle or a check box to auto route all non-existing domains back to one I can set somewhere here.
<img width="861" alt="Screen Shot 2023-08-19 at 2 19 33 PM" src="https://github.com/tobychui/zoraxy/assets/82685579/11543189-bc66-4ec6-9667-d9d7b8bdb08c">

nonexisting.abc.xyz redirects to root.abc.xyx and replies with root.abc.xyx SSL cert

option 2.
Add wildcard domain SSL certs with ACME (will need to implement DNS SSL cert generation)
This will mitigate the issue and will be preferred as it will still keep the nonexisting URL but will still have a valid SSL cert.

**Describe alternatives you've considered**
I tried to add a *.domain.root as a new proxy rule, but it is expecting %2A.abc.xyz instead of *.abc.xyz

**Comment by tobychui** [comment]
Hi @stevewas ,

The reason why it is responding with a self signed cert (or dummy cert) is because you didn't upload the default certificate. Please make sure there are two green checkmarks on this page
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/7587dba7-e020-49b4-970f-c36f937c0e75)

Can you try uploading a wild-card certificate as the default cert in the TLS/SSL management page and see if that solved your issue?

By default, all non-existsing subdomains will get forwarded to root proxy. I guess I can add a redirection override (instead of proxying like a normal sub-domain to root address) when a subdomain is not found, but this feature worth a new enhancement issue on its own (if you want this feature added, please feel free to open a new issue :) )

**Comment by stevewas** [comment]
So I got it working with the wildcard SSL certs by manually uploading it. However, it would have been better to have Zoraxy have it automated.

In that case, this can probably be merged with #49 and #6

But for  proxying to root when a subdomain is not found, you can either use this ENHANCEMENTS issue (which is what I wanted this ticket to be originally)

**Comment by tobychui** [comment]
Feature added in v2.6.6. You can find this feature under Set Proxy Root > Root Routing Options
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/3f45682a-4971-4c5e-9af2-54230954e952)

Here are two tips on how to use it
- You can leave it empty to redirect to the first level of redirectable domain (e.g. notfound.service.example.com -> example.com)
- You can set a custom URL there for redirecting (e.g. notfound.service.example.com -> https://myhomepage.com)
