### ISSUE TITLE
[BUG] Service Expose Proxy Page Blank

### ISSUE THREAD

**Issue by definedlegend** [tobychui/zoraxy#58]
**Describe the bug**
Not completely sure if this is a bug or I just have to disable/enable a feature to use this page but when I click on service expose proxy it loads a blank page. 
**To Reproduce**
1. Go to Service Expose Proxy 
2. Click on it under bridging to open
3. Presented with blank page on service expose proxy

**Expected behavior**
I expect the service expose proxy to load and show what the page is for and to be used for. I also expect the global area network 

**Screenshots**
[Screenshot of issue](https://imgur.com/a/RxzaVkF)

**Browser (if it is a bug appears on the UI section of the system):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [chrome Version 116.0.5845.141 and Zoraxy Version 2.6.5 Docker Image zoraxydocker/zoraxy:latest]

**Host Environment (please complete the following information):**
-  Arch: [arm64]
 - Device: [Intel i7-8700 128gb Ram]
 - OS: [e.g. Debian]
 - Version [12]

**Additional context**
Running under zoraxydocker/zoraxy:latest docker

**Comment by tobychui** [comment]
Yes, the blank page on service expose proxy is perfectly normal. 

This is currently a blank page because I am too busy fixing issues with the core reverse proxy and there aren't any contributors want to help write that feature yet. (sorry for this if this is the feature you are looking forward to :( )

If you are interested to contribute, feel free to let me know!
