### ISSUE TITLE
[BUG]SMTP without auth

### ISSUE THREAD

**Issue by barto95100** [tobychui/zoraxy#78]
How its possible to use SMTP without auth on port 25 ? 
When I test ziraxy inficate the configuration is not ok because no user/password added : 
![CleanShot 2023-11-16 at 12 59 15@2x](https://github.com/tobychui/zoraxy/assets/17863254/cb2ff4f7-606c-4589-bf9e-a5f390661a23)
and smtp server not possible with ip ... :(

**Comment by tobychui** [comment]
Hi @barto95100,

This is not a bug nor this issue is a useful bug report. Zoraxy shows error here just because it is not designed for self-host password-less SMTP server. If you want this feature, feel free to modify the code (and create a pull request) or create a feature request.

Otherwise, if you truly believe this is a bug, please provide more information regarding your setups, infrastructures and detail steps on how to recreate it.
