### ISSUE TITLE
[ENHANCEMENTS] Dark Theme

### ISSUE THREAD

**Issue by Dvalin21** [tobychui/zoraxy#82]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [.Yes, Just started using this awesome application today. Thank you for all the work that you and however else put into this. Requesting for change of theme function. More specifically Dark/Black theme. Make it a little easier on the eyes. Thanks in advance...]

**Describe the solution you'd like**
Dark Theme created

**Comment by kmanwar89** [comment]
Any chance this has been considered? Dark theme is almost a must these days!

**Comment by tobychui** [comment]
@kmanwar89 As you can see, this enhancement request is not closed or getting a "won't fix" label, that means this is being considered. However, as I only work on this project in my free time, I usually prioritize fixing / implementing core functions that is critical to the reverse proxy functionality instead of utilities functions like dark-theme. 

As always, PRs are welcomed. If you know how to write a css theme, feel free to create a pull request with the changes you want and tag me for a quick review :)

**Comment by JcMinarro** [comment]
I can see some dark-theme css are added to [this](https://github.com/tobychui/zoraxy/blob/main/src/web/main.css#L30) and the "theme toggle button" is commented [here](https://github.com/tobychui/zoraxy/blob/main/src/web/index.html#L33).
The dark-theme is enabled by calling `toggleTheme()` within the browser's console.

Is this feature disabled because the Dark CSS has not been completed?

**Comment by tobychui** [comment]
> Is this feature disabled because the Dark CSS has not been completed?

@JcMinarro Yes. I kinda want to complete it but currently I am flooded with bugs related to ACME and external services that I don't have much time to complete it. You would like to help me out on this?

**Comment by JcMinarro** [comment]
I don't have high css knowledge, but I will try to improve it a bit

**Comment by BadFlo** [comment]
@Dvalin21, a wider fix could be using a browser extension like [Dark Reader](https://chromewebstore.google.com/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh) in the time being.

**Comment by tobychui** [comment]
Dark theme is working in progress, but the workload is too much that I think it will takes a few more months (at least) to be usable. But here is the preview.

![圖片](https://github.com/user-attachments/assets/496284ad-5a77-4e83-b81c-6a5382a056cf)

**Comment by tobychui** [comment]
Dark theme mode added in v3.1.4.
