### ISSUE TITLE
[BUG]Send X-forwarder-ip or X-real-ip ? 

### ISSUE THREAD

**Issue by barto95100** [tobychui/zoraxy#93]
when I check the log on nginx behind zoraxy I don't view the real ip but the zoraxy ip ? 

It's necessary to configure option or other to send x-real-ip or x-forwarder-ip ? @tobychui

**Comment by Cerothen** [comment]
I agree with this issue as well, not having the x-real-ip or x-forwarder-ip headers set can cause issues for various background services.

It would additionally be beneficial to have some advanced options:
1. Allow specifying upstream trusted proxy IP addresses, do not replace the headers if the upstream proxy is trusted.
2. Unset x-real-ip or x-forwarder-ip headers sent from untrusted proxies upstream

**Comment by tobychui** [comment]
The current implementation already copies (& append, if zoraxy is not the first reverse proxy) the original request ip address to X-Forwarded-For header. See here for more information.

https://github.com/tobychui/zoraxy/blob/d6e7641364ac6ed1282b5dd4b27da02c4acf2564/src/mod/dynamicproxy/dpcore/dpcore.go#L269

I can add X-real-ip as well but I don't think it is strictly necessary.

**Comment by Cerothen** [comment]
Zoraxy should discard the upstream x-real-ip or x-forwarder-ip headers unless they specifically come from a trusted proxy IP address as it would cause a security risk of outside requests pretending to be internal requests or requests coming from a trusted address

**Comment by tobychui** [comment]
@Cerothen It is not Zoraxy's job to discard the unsafe IP in x-forwarder-ip for you. We follows the design of AWS cloud service which appends the client IP (from what Zoraxy saw) to the end of the ip list as described [here](https://www.stackhawk.com/blog/do-you-trust-your-x-forwarded-for-header/).

> AWS strictly appends a single IP address of the calling client to the X-Forwarded-For header.
>`AWS: 'X-Forwarded-For: <whatever-was-on-the-request-before>, <aws-detected-client-ip>'`

To avoid untrusted requests, you should implement such filter in the backend server where you are proxying to, instead of offloading such job to reverse proxy server. Alternatively, you can make use of Zoraxy's whitelist features to block untrusted access to your servers (currently this feature only support global scope access control).

**Comment by barto95100** [comment]
Maybe if it’s possible for you add thé X-real-ip ?

Because For example zoraxy is front of discourse forum and the discourse rate limited because is check the X-real-ip and not x-forwarder-ip, and the discourse block/blackliste/limite request because discourse view the ip of zoraxy….

thank’s

**Comment by tobychui** [comment]
@barto95100 For your information, I didn't do anything to the X-real-ip header regarding any request passing through Zoraxy. 
In the current implementation, if the incoming request carries the X-real-ip header, it will be copied to the outgoing one (to your reverse proxy target). But if the incoming one didn't carries the X-real-ip header, it will not exists in the outgoing request.

I guess in this case, **I can add X-Real-Ip equal to the remote address which I extract from X-Forwarded-For if X-real-ip do not exists in incoming request and X-Forwarded-For exists.**

You sure this is what you want and expected?

**Comment by barto95100** [comment]
YEs but if the x-real-ip is present zoraxy don't touch or modify to backend

**Comment by tobychui** [comment]
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/65501c84-c5b7-4e27-bf24-48eb78555cf0)

X-real-ip added in internal preview of Zoraxy v3.0.0. 
Will be closing this after release.

**Comment by RTechSn** [comment]
I apologize for commenting into a closed issue, but how do I enable it? Or is it enabled by default?
My Meshcentral instance requires X-Forwarded-For header to show machine IPs, but right now it shows IP of the reverse proxy.

**Comment by tobychui** [comment]
@RTechSn Yes, it is enabled by default. 

The behavior you are having are very likely because Meshcentral do not parse the `X-Forarded-For` according to the [specification](https://developer.mozilla.org/zh-TW/docs/Web/HTTP/Reference/Headers/X-Forwarded-For). The specification requires the `X-Forwaded-For` format as

```
X-Forwarded-For: <client>, <proxy1>, <proxy2>
```

but many projects out there only extract the last valid IP from the `X-Forwarded-For` list (`<proxy2>` in the above example), which I am not sure if it is a de-facto standard or there is a bug in a commonly used library of some sort.

I guess you can overwrite it with the `$remote_addr` or `$remote_ip` (coming soon in v3.2.1) via custom headers if needed.
